<?php
$CONFIG = array (
  'htaccess.RewriteBase' => '/',
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'apps_paths' => 
  array (
    0 => 
    array (
      'path' => '/var/www/html/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 => 
    array (
      'path' => '/var/www/html/custom_apps',
      'url' => '/custom_apps',
      'writable' => true,
    ),
  ),
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' => 
  array (
    'host' => 'hermes_nextcloud_redis',
    'password' => 'be05411046a008016c60cdbd2891279af78efcd7b35904ac',
    'port' => 6379,
  ),
  'overwriteprotocol' => 'https',
  'overwritewebroot' => '/nc',
  'trusted_proxies' => 
  array (
    0 => '172.16.0.0/12',
    1 => '127.0.0.1',
  ),
  'allow_local_remote_servers' => true,
  'mail_smtpmode' => 'smtp',
  'mail_smtphost' => 'host.docker.internal',
  'mail_smtpport' => '10026',
  'mail_smtpsecure' => '',
  'mail_smtpauth' => false,
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpname' => '',
  'mail_from_address' => 'postmaster',
  'mail_domain' => 'deeztek.net',
  'mail_smtppassword' => '',
  'upgrade.disable-web' => true,
  'passwordsalt' => '2M8JaEirnMAcs/gWidYSxmBGjY2yJH',
  'secret' => '+ivmFgG1tA5KGz/I6FwpVMp9zkEINt+9jcnjMtzpLBto9WC8',
  'trusted_domains' => 
  array (
    0 => 'localhost',
    1 => 'smtp-dev.deeztek.com',
    2 => '192.168.50.145',
  ),
  'datadirectory' => '/var/www/html/data',
  'dbtype' => 'mysql',
  'version' => '30.0.14.1',
  'overwrite.cli.url' => 'https://localhost/nc',
  'dbname' => 'nextcloud',
  'dbhost' => 'host.docker.internal:3306',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => 'public28314',
  'dbpassword' => 'bdc767b98c94ce7b326e24d6bd025ac5aebcc245942543db',
  'installed' => true,
  'instanceid' => 'oc2niwy6bubk',
  'defaultapp' => 'mail',
  'lost_password_link' => 'disabled',
  'oidc_login_provider_url' => 'https://smtp-dev.deeztek.com',
  'oidc_login_client_id' => 'Hermes_SEG_Webmail',
  'oidc_login_client_secret' => 'OIDC_LOGIN_CLIENT_SECRET',
  'oidc_login_auto_redirect' => false,
  'oidc_login_logout_url' => '/users/logout.cfm',
  'oidc_login_end_session_redirect' => false,
  'oidc_login_button_text' => 'Click to Login to Webmail',
  'oidc_login_hide_password_form' => true,
  'oidc_login_use_id_token' => true,
  'oidc_login_attributes' => 
  array (
    'id' => 'preferred_username',
    'name' => 'name',
    'mail' => 'email',
    'groups' => 'groups',
  ),
  'oidc_login_allowed_groups' => 
  array (
    0 => 'mailboxes',
  ),
  'oidc_login_default_group' => '',
  'oidc_login_use_external_storage' => false,
  'oidc_login_scope' => 'openid profile email groups',
  'oidc_login_proxy_ldap' => false,
  'oidc_login_disable_registration' => false,
  'oidc_login_redir_fallback' => false,
  'oidc_login_tls_verify' => true,
  'oidc_create_groups' => false,
  'oidc_login_webdav_enabled' => true,
  'oidc_login_password_authentication' => true,
  'oidc_login_public_key_caching_time' => 86400,
  'oidc_login_min_time_between_jwks_requests' => 10,
  'oidc_login_well_known_caching_time' => 86400,
  'oidc_login_update_avatar' => false,
  'loglevel' => 2,
  'maintenance' => false,
);
