server {
        listen 443 ssl;
        server_name hermes_server_name;
        hermes_hsts;
        keepalive_timeout   70;
        access_log /var/log/nginx/hermes_access.log;
        error_log /var/log/nginx/hermes_error.log warn;
        ssl_certificate     hermes_ssl_certificate;
        ssl_certificate_key hermes_ssl_key;
        hermes_ocsp;
        hermes_verify;
        ssl_protocols       TLSv1.2 TLSv1.3;
        ssl_ciphers 'EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH';
        hermes_dhparam_file;
        ssl_prefer_server_ciphers on;
        ssl_session_cache shared:SSL:10m;
        proxy_max_temp_file_size 5120m;
        client_max_body_size 5120m;


location / {
        return 301 https://hermes_console_host$request_uri;
}

}

