DomainWhitelistFile /etc/opendmarc/whitelist.domains
FailureReports false
HistoryFile /etc/opendmarc/opendmarc.dat
HoldQuarantinedMessages false
IgnoreHosts /opt/hermes/dkim/TrustedHosts
PidFile /var/run/opendmarc/opendmarc.pid
PublicSuffixList /usr/share/publicsuffix
RejectFailures true
Socket inet:54321@0.0.0.0
Syslog true
UserID opendmarc



