#!/bin/sh
# Detect which iptables backend the host uses and configure fail2ban accordingly
# Docker typically uses iptables-legacy, but some hosts may use iptables-nft
#
# This script runs at container startup and creates .local override files
# for our custom Hermes actions to use the correct iptables binary.

IPTABLES_BACKEND=""

echo "=== Detecting iptables backend ==="

# Check for "legacy tables" warning which indicates
# the system is using legacy backend but we're querying with nft
# The full message is: "Warning: iptables-legacy tables present, use iptables-legacy to see them"
# We match on "legacy tables" to catch any variations
NFT_HAS_LEGACY_WARNING=$(iptables-nft -L DOCKER -n 2>&1 | grep -ci "legacy tables")

if [ "$NFT_HAS_LEGACY_WARNING" -gt 0 ]; then
    # nft command shows warning about legacy tables - use legacy
    IPTABLES_BACKEND="iptables-legacy"
    echo "Detected iptables-legacy backend (nft showed legacy warning)"
# Check if iptables-legacy has Docker rules (DOCKER chain) without warnings
elif iptables-legacy -L DOCKER -n 2>&1 | grep -q "^Chain DOCKER"; then
    IPTABLES_BACKEND="iptables-legacy"
    echo "Detected iptables-legacy backend (Docker chain found)"
# Check if iptables-nft has Docker rules without the legacy warning
elif iptables-nft -L DOCKER -n 2>&1 | grep -q "^Chain DOCKER"; then
    IPTABLES_BACKEND="iptables-nft"
    echo "Detected iptables-nft backend (Docker chain found)"
# Fallback: check which one has any INPUT rules
elif iptables-legacy -L INPUT -n 2>/dev/null | grep -q -v "^Chain\|^target"; then
    IPTABLES_BACKEND="iptables-legacy"
    echo "Detected iptables-legacy backend (INPUT rules found)"
elif iptables-nft -L INPUT -n 2>/dev/null | grep -q -v "^Chain\|^target"; then
    IPTABLES_BACKEND="iptables-nft"
    echo "Detected iptables-nft backend (INPUT rules found)"
else
    # Default to legacy as it's more common with Docker
    IPTABLES_BACKEND="iptables-legacy"
    echo "Could not detect backend, defaulting to iptables-legacy"
fi

echo "Using iptables backend: $IPTABLES_BACKEND"

# Create .local override files for each Hermes action
# fail2ban loads .local files AFTER .conf files, so these will override
# the hardcoded iptables value in the .conf files

echo "Creating .local override files for Hermes actions..."

# Override for dovecot action
cat > /config/fail2ban/action.d/hermes-iptables-dovecot.local << EOF
# Auto-generated by detect-iptables-backend.sh
# Overrides iptables binary based on detected host backend
[Init]
iptables = $IPTABLES_BACKEND
EOF

# Override for authelia action
cat > /config/fail2ban/action.d/hermes-iptables-authelia.local << EOF
# Auto-generated by detect-iptables-backend.sh
# Overrides iptables binary based on detected host backend
[Init]
iptables = $IPTABLES_BACKEND
EOF

echo "Created override files:"
echo "  - /config/fail2ban/action.d/hermes-iptables-dovecot.local"
echo "  - /config/fail2ban/action.d/hermes-iptables-authelia.local"
echo "=== iptables backend detection complete ==="
