#!/bin/sh
# Hermes SEG - API Notification Script
# Called by fail2ban actions to log bans/unbans in the Hermes database
# Blocking is handled by iptables (fail2ban's native mechanism)
#
# Usage: hermes-api-notify.sh <ACTION> <IP> <SOURCE>
#   ACTION: BAN or UNBAN
#   IP: The IP address being banned/unbanned
#   SOURCE: MAILSERVER, SSO, or ADMIN
#
# Note: This container uses network_mode: host, so we use the container IPs
# directly since Docker DNS names are not available in host network mode.
# Container IPs are read from a file generated by hermes_commandbox.

ACTION=$1
IP=$2
SOURCE=$3
TYPE=AUTOMATIC

# Container IPs file (generated by CFML in commandbox, overwritten on each page load)
CONTAINER_IPS_FILE="/opt/hermes/tmp/container_ips.env"

if [ ! -f "$CONTAINER_IPS_FILE" ]; then
    # File doesn't exist - IPs not yet generated
    exit 0
fi

# Source the container IPs file
. "$CONTAINER_IPS_FILE"
DB_IP="${HERMES_DB_IP}"
COMMANDBOX_IP="${HERMES_COMMANDBOX_IP}"

if [ -z "$DB_IP" ] || [ -z "$COMMANDBOX_IP" ]; then
    # IPs not found in file
    exit 0
fi

# Debug logging
DATE=$(date)
echo "[$DATE] API Notify: Action=$ACTION IP=$IP Source=$SOURCE DB=$DB_IP CB=$COMMANDBOX_IP" >> /scripts/api-notify.log

# Get Hermes MySQL credentials
HERMES_USERNAME=$(cat /opt/hermes/creds/hermes_username 2>/dev/null)
HERMES_PASSWORD=$(cat /opt/hermes/creds/hermes_password 2>/dev/null)

if [ -z "$HERMES_USERNAME" ] || [ -z "$HERMES_PASSWORD" ]; then
    echo "[$DATE] ERROR: Missing creds files" >> /scripts/api-notify.log
    exit 1
fi

# Get API token from database
THETOKEN=$(mariadb -h $DB_IP -P 3306 -u $HERMES_USERNAME -p$HERMES_PASSWORD hermes -se "SELECT token FROM api_tokens WHERE name='Fail2ban' AND system='1' AND active='1'" 2>/dev/null)

echo "[$DATE] Token result: '${THETOKEN:0:8}...'" >> /scripts/api-notify.log

# Call Hermes API to log the ban/unban in the database
if [ -n "$THETOKEN" ]; then
    API_RESULT=$(curl -X "POST" -s -w "\nHTTP_CODE:%{http_code}" "http://${COMMANDBOX_IP}:8888/hermes-api/" \
        -H "accept: */*" \
        -H "X-Original-URL: /admin/2/inc/fail2ban_ban_unban.cfm?action=$ACTION&ip=$IP&type=$TYPE&source=$SOURCE" \
        -H "X-Token: $THETOKEN" 2>&1)
    echo "[$DATE] API result: ${API_RESULT}" >> /scripts/api-notify.log
else
    echo "[$DATE] ERROR: No token returned from database" >> /scripts/api-notify.log
fi
