#!/bin/sh
# Hermes SEG - fail2ban ban/unban notification
# Called by fail2ban actions to record bans/unbans in the Hermes database.
# Blocking itself is done by iptables (fail2ban's native mechanism).
#
# Usage: hermes-api-notify.sh <ACTION> <IP> <SOURCE>
#   ACTION: BAN or UNBAN
#   IP: The IP address being banned/unbanned
#   SOURCE: MAILSERVER, SSO, or ADMIN
#
# This container uses network_mode: host, so Docker DNS names are not
# available. The CommandBox address comes from HERMES_COMMANDBOX_IP (set in
# docker-compose.yml), falling back to the file generated by hermes_commandbox.

ACTION=$1
IP=$2
SOURCE=$3
TYPE=AUTOMATIC
DATE=$(date)
LOG=/scripts/api-notify.log

COMMANDBOX_IP="${HERMES_COMMANDBOX_IP:-}"
CONTAINER_IPS_FILE="/opt/hermes/tmp/container_ips.env"
if [ -z "$COMMANDBOX_IP" ] && [ -f "$CONTAINER_IPS_FILE" ]; then
    . "$CONTAINER_IPS_FILE"
    COMMANDBOX_IP="${HERMES_COMMANDBOX_IP:-}"
fi

if [ -z "$COMMANDBOX_IP" ]; then
    echo "[$DATE] ERROR: CommandBox address unknown; $ACTION $IP not recorded" >> "$LOG"
    exit 0
fi

RESULT=$(curl -s -G -w "\nHTTP_CODE:%{http_code}" "http://${COMMANDBOX_IP}:8888/schedule/fail2ban_ban_unban.cfm" \
    --data-urlencode "action=$ACTION" \
    --data-urlencode "ip=$IP" \
    --data-urlencode "type=$TYPE" \
    --data-urlencode "source=$SOURCE" 2>&1)
echo "[$DATE] $ACTION $IP ($SOURCE): ${RESULT}" >> "$LOG"
