## You should mount /etc/dovecot if you want to
## manage this file

mail_home = /srv/mail/%d/%n
mail_location = maildir:~/
mail_plugins = $mail_plugins quota zlib mail_crypt
mail_uid = 1000
mail_gid = 1000
mail_privileged_group = mail
mail_debug = yes
auth_debug = yes

protocols = imap pop3 submission sieve lmtp



first_valid_uid = 1000
last_valid_uid = 1000

login_trusted_networks = 172.16.32.0/24

#Quote Config
dict {
quotadict = mysql:/etc/dovecot/dovecot-dict-sql-quota.conf
}

service dict {
	unix_listener dict {
		group = vmail
		mode = 0660
		user = vmail
	}
	user = root
}


plugin {
       quota = dict:Userquota::proxy::quotadict
       quota_rule2 = Trash:storage=+10%%
       quota_warning = storage=99%% quota-warning +99 %u
       quota_warning2 = storage=95%% quota-warning +95 %u
       quota_warning3 = storage=80%% quota-warning +80 %u
       quota_warning4 = -storage=100%% quota-warning -100 %u # user is no longer over quota
}

service quota-warning {
	executable = script /scripts/quota-warning.sh
	user = vmail
	unix_listener quota-warning {
		group = vmail
		mode = 0660
		user = vmail
	}
}	


protocol imap {
        mail_plugins = $mail_plugins imap_quota zlib mail_crypt
        imap_metadata = yes
}


protocol lmtp {
  mail_plugins = quota sieve mail_crypt
}

protocol sieve {
  managesieve_logout_format = bytes=%i/%o
}

protocol pop3 {
	 mail_plugins = $mail_plugins mail_crypt
	 pop3_client_workarounds = outlook-no-nuls oe-ns-eoh
	 pop3_uidl_format = %08Xu%08Xv
}



plugin {
  # Used by both the Sieve plugin and the ManageSieve protocol
  sieve = /srv/mail/sieve/%u.sieve
}

plugin {
  # Enable compression when saving
  zlib_save = lz4
}


plugin {
  mail_crypt_global_private_key = </keys/ecprivkey.pem
  mail_crypt_global_public_key = </keys/ecpubkey.pem
  mail_crypt_curve = prime256v1
  mail_crypt_save_version = 2
}


#sieve = /srv/mail/sieve/%u.sieve

namespace {
  inbox = yes
  separator = /

 mailbox Trash {
    auto = subscribe
    special_use = \Trash
  }
  mailbox Sent {
    auto = subscribe
    special_use = \Sent
  }
  mailbox Drafts {
    auto = subscribe
    special_use = \Drafts
  }
  mailbox Spam {
    auto = subscribe
    special_use = \Junk
  }
  mailbox Archive {
    auto = subscribe
    special_use = \Archive
  }
}

service lmtp {
  inet_listener {
    port = 24
  }
}

service imap-login {
  process_min_avail = 1
  client_limit = 1000
  service_count = 0
}

service pop3-login {
  process_min_avail = 1
  client_limit = 1000
  service_count = 0
}

service submission-login {
  process_min_avail = 1
  client_limit = 1000
  service_count = 0
}

service managesieve-login {
  process_min_avail = 1
  client_limit = 1000
  service_count = 0
}

service auth {
  inet_listener auth-inet {
    port = 9587
  }
}


listen = *

#log_path=/dev/stdout
#info_log_path=/dev/stdout
#debug_log_path=/dev/stdout

log_path=/logs/dovecot.log
info_log_path=/logs/dovecot-info.log
debug_log_path=/logs/dovecot-debug.log


verbose_proctitle = yes

!include_try /etc/dovecot/conf.d/*.conf
