server {
        listen 443 ssl;
        server_name autoconfig.deeztek.net autodiscover.deeztek.net;
        add_header Strict-Transport-Security "max-age=31536000; preload";
        keepalive_timeout   70;
        access_log /var/log/nginx/hermes_access.log;
        error_log /var/log/nginx/hermes_error.log warn;
        ssl_certificate     /etc/letsencrypt/live/deeztek.net/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/deeztek.net/privkey.pem;
        ssl_stapling on;
        ssl_stapling_verify on;
        ssl_protocols       TLSv1.2 TLSv1.3;
        ssl_ciphers 'EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH';
        ssl_dhparam /opt/hermes/ssl/dhparam.pem;
        ssl_prefer_server_ciphers on;
        ssl_session_cache shared:SSL:10m;
        proxy_max_temp_file_size 5120m;
        client_max_body_size 5120m;


location / {
        return 301 https://smtp-dev.deeztek.com$request_uri;
}

}

