connect = "host=hermes_db_server dbname=hermes user=hermes password=bfrJJDnEb5mv8G8Is5T1"

map {
	pattern = priv/quota/storage
	table = quota2
	username_field = username
	value_field = bytes
}
map {
	pattern = priv/quota/messages
	table = quota2
	username_field = username
	value_field = messages
}
