### Configuration file for rsyslog-mysql
### Changes are preserved

#$ModLoad ommysql
#local4.* :ommysql:hermes_db_server,Syslog,rsyslog,p3nHPo5e6JtPaDoo7itV

$ModLoad ommysql

if ($programname == "slapd") then {
  action(type="ommysql"
         server="hermes_db_server"
         db="Syslog"
         uid="rsyslog"
         pwd="p3nHPo5e6JtPaDoo7itV")
  stop
}



