#encoding=UTF-8

# this file can contain one or more parameters that will be passed as is to the JVM 
# example:
# -Dciphermail.hibernate.database.type=mysql
-Dciphermail.hibernate.database.type=mysql
