
<!---
Hermes Secure Email Gateway Copyright Dionyssios Edwards 2011-2026. All Rights Reserved.

GENERATE UNBOUND LOCAL.CONF
Reads local DNS overrides from dns_local_records table and generates
/etc/unbound/conf.d/local.conf. Then restarts Unbound.
--->

<!--- Read enabled local records --->
<cfquery name="getLocalRecords" datasource="hermes">
    SELECT hostname, record_type, value FROM dns_local_records
    WHERE enabled = 1 ORDER BY hostname ASC
</cfquery>

<!--- Build local.conf --->
<cfset nl = chr(10)>
<cfset conf = chr(35) & " Unbound DNS Resolver - Local Zone Overrides" & nl>
<cfset conf = conf & chr(35) & " Generated by Hermes SEG Admin UI" & nl>
<cfset conf = conf & chr(35) & " " & DateTimeFormat(Now(), "yyyy-MM-dd HH:nn:ss") & nl>
<cfset conf = conf & nl>

<!--- Group records by hostname to create local-zone + local-data entries --->
<cfset processedZones = StructNew()>
<cfloop query="getLocalRecords">
    <!--- Extract the zone (top 2 domain parts) from hostname --->
    <cfset hostParts = ListToArray(getLocalRecords.hostname, ".")>
    <cfif ArrayLen(hostParts) GTE 2>
        <cfset zoneName = hostParts[ArrayLen(hostParts) - 1] & "." & hostParts[ArrayLen(hostParts)]>
    <cfelse>
        <cfset zoneName = getLocalRecords.hostname>
    </cfif>

    <!--- Add transparent zone declaration (only once per zone) --->
    <cfif NOT StructKeyExists(processedZones, zoneName)>
        <cfset conf = conf & 'local-zone: "' & zoneName & '." transparent' & nl>
        <cfset processedZones[zoneName] = true>
    </cfif>

    <!--- Add local-data entry --->
    <cfset conf = conf & 'local-data: "' & getLocalRecords.hostname & '. IN ' & getLocalRecords.record_type & ' ' & getLocalRecords.value & '"' & nl>
</cfloop>

<cfif getLocalRecords.recordcount EQ 0>
    <cfset conf = conf & chr(35) & " No local DNS overrides configured." & nl>
</cfif>

<!--- Write local.conf --->
<cfscript>fileWrite("/etc/unbound/conf.d/local.conf", conf, "utf-8");</cfscript>

<!--- Restart Unbound --->
<cfexecute name="/usr/local/bin/docker"
    arguments="container restart hermes_unbound"
    variable="restartResult"
    errorVariable="restartError"
    timeout="30" />
