
<!---
Hermes Secure Email Gateway Copyright Dionyssios Edwards 2011-2026. All Rights Reserved.

GENERATE UNBOUND FORWARD.CONF
Reads forwarding settings from parameters2 (module='unbound') and generates
/etc/unbound/conf.d/forward.conf. Then restarts the Unbound container.

Called after saving DNS Resolver settings from the admin UI.
--->

<!--- Read settings from database --->
<cfquery name="getUnboundSettings" datasource="hermes">
    SELECT parameter, value2 FROM parameters2 WHERE module = 'unbound'
</cfquery>

<cfset ub = StructNew()>
<cfloop query="getUnboundSettings">
    <cfset ub[getUnboundSettings.parameter] = getUnboundSettings.value2>
</cfloop>

<!--- Defaults --->
<cfparam name="ub['forwarding.enabled']" default="no">
<cfparam name="ub['forwarding.tls']" default="no">
<cfparam name="ub['forwarding.server1']" default="">
<cfparam name="ub['forwarding.server2']" default="">
<cfparam name="ub['forwarding.server3']" default="">
<cfparam name="ub['forwarding.server4']" default="">

<!--- Build forward.conf content --->
<cfset nl = chr(10)>
<cfset forwarderConf = chr(35) & " Unbound DNS Resolver - Upstream Forwarders" & nl>
<cfset forwarderConf = forwarderConf & chr(35) & " Generated by Hermes SEG Admin UI" & nl>
<cfset forwarderConf = forwarderConf & chr(35) & " " & DateTimeFormat(Now(), "yyyy-MM-dd HH:nn:ss") & nl>
<cfset forwarderConf = forwarderConf & nl>

<cfif ub['forwarding.enabled'] EQ "yes">
    <cfset forwarderConf = forwarderConf & "forward-zone:" & nl>
    <cfset forwarderConf = forwarderConf & "    name: "".""" & nl>
    <cfset forwarderConf = forwarderConf & "    forward-tls-upstream: " & ub['forwarding.tls'] & nl>
    <cfloop list="forwarding.server1,forwarding.server2,forwarding.server3,forwarding.server4" index="key">
        <cfif StructKeyExists(ub, key) AND Trim(ub[key]) NEQ "">
            <cfset forwarderConf = forwarderConf & "    forward-addr: " & Trim(ub[key]) & nl>
        </cfif>
    </cfloop>
<cfelse>
    <cfset forwarderConf = forwarderConf & chr(35) & " Forwarding disabled - Unbound performs full recursive resolution" & nl>
    <cfset forwarderConf = forwarderConf & chr(35) & " Recommended for email servers (reliable RBL/DNSBL lookups)" & nl>
</cfif>

<!--- Write forward.conf to mounted config directory --->
<cfscript>
    fileWrite("/etc/unbound/conf.d/forward.conf", forwarderConf, "utf-8");
</cfscript>

<!--- Restart Unbound to apply --->
<cfexecute name="/usr/local/bin/docker"
    arguments="container restart hermes_unbound"
    variable="restartResult"
    errorVariable="restartError"
    timeout="30" />
