
<!---
Hermes Secure Email Gateway Copyright Dionyssios Edwards 2011-2026. All Rights Reserved.

GENERATE UNBOUND FORWARD.CONF
Reads forwarding settings from parameters2 and dns_forwarders table,
generates /etc/unbound/conf.d/forward.conf, then restarts Unbound.
--->

<!--- Read global forwarding toggle --->
<cfquery name="getForwardingEnabled" datasource="hermes">
    SELECT value2 FROM parameters2 WHERE module = 'unbound' AND parameter = 'forwarding.enabled'
</cfquery>
<cfset fwdEnabled = "no">
<cfif getForwardingEnabled.recordcount GTE 1>
    <cfset fwdEnabled = getForwardingEnabled.value2>
</cfif>

<!--- Read enabled forwarders --->
<cfquery name="getForwarders" datasource="hermes">
    SELECT server, port, tls FROM dns_forwarders WHERE enabled = 1 ORDER BY sort_order ASC
</cfquery>

<!--- Build forward.conf --->
<cfset nl = chr(10)>
<cfset conf = chr(35) & " Unbound DNS Resolver - Upstream Forwarders" & nl>
<cfset conf = conf & chr(35) & " Generated by Hermes SEG Admin UI" & nl>
<cfset conf = conf & chr(35) & " " & DateTimeFormat(Now(), "yyyy-MM-dd HH:nn:ss") & nl>
<cfset conf = conf & nl>

<cfif fwdEnabled EQ "yes" AND getForwarders.recordcount GT 0>
    <cfset conf = conf & "forward-zone:" & nl>
    <cfset conf = conf & "    name: "".""" & nl>
    <!--- Check if any forwarder uses TLS --->
    <cfset useTls = false>
    <cfloop query="getForwarders">
        <cfif getForwarders.tls EQ 1>
            <cfset useTls = true>
        </cfif>
    </cfloop>
    <cfset conf = conf & "    forward-tls-upstream: " & (useTls ? "yes" : "no") & nl>
    <cfloop query="getForwarders">
        <cfif getForwarders.tls EQ 1>
            <cfset conf = conf & "    forward-addr: " & getForwarders.server & "@" & getForwarders.port & nl>
        <cfelse>
            <cfset conf = conf & "    forward-addr: " & getForwarders.server & nl>
        </cfif>
    </cfloop>
<cfelse>
    <cfset conf = conf & chr(35) & " Forwarding disabled - Unbound performs full recursive resolution" & nl>
    <cfset conf = conf & chr(35) & " Recommended for email servers (reliable RBL/DNSBL lookups)" & nl>
</cfif>

<!--- Write forward.conf --->
<cfscript>fileWrite("/etc/unbound/conf.d/forward.conf", conf, "utf-8");</cfscript>

<!--- Restart Unbound --->
<cfexecute name="/usr/local/bin/docker"
    arguments="container restart hermes_unbound"
    variable="restartResult"
    errorVariable="restartError"
    timeout="30" />
