
<!---
Hermes Secure Email Gateway Copyright Dionyssios Edwards 2011-2026. All Rights Reserved.

GENERATE UNBOUND LOCAL.CONF
Reads local DNS overrides from dns_local_records table and generates
/etc/unbound/conf.d/local.conf. Then restarts Unbound.
--->

<!--- Read enabled local records --->
<cfquery name="getLocalRecords" datasource="hermes">
    SELECT hostname, record_type, value FROM dns_local_records
    WHERE enabled = 1 ORDER BY hostname ASC
</cfquery>

<!--- Build local.conf --->
<cfset nl = chr(10)>
<cfset conf = chr(35) & " Unbound DNS Resolver - Local Zone Overrides" & nl>
<cfset conf = conf & chr(35) & " Generated by Hermes SEG Admin UI" & nl>
<cfset conf = conf & chr(35) & " " & DateTimeFormat(Now(), "yyyy-MM-dd HH:nn:ss") & nl>
<cfset conf = conf & nl>

<!--- The `server:` header is REQUIRED, not cosmetic. unbound.conf opens a
     server: clause and then includes conf.d/forward.conf BEFORE this file.
     When forwarding is enabled (the default install mode) forward.conf
     contains a `forward-zone:` clause, which closes server: -- so anything
     emitted here lands inside forward-zone:, where local-zone and local-data
     are not valid and unbound dies at startup with
     "conf.d/local.conf:N: error: syntax error", taking DNS down for the whole
     stack. Declaring our own server: clause makes this file valid regardless
     of what precedes it (#304). --->
<cfset conf = conf & "server:" & nl>

<!--- Group records by hostname to create local-zone + local-data entries --->
<cfset processedZones = StructNew()>
<cfloop query="getLocalRecords">
    <!--- Extract the zone (top 2 domain parts) from hostname --->
    <cfset hostParts = ListToArray(getLocalRecords.hostname, ".")>
    <cfif ArrayLen(hostParts) GTE 2>
        <cfset zoneName = hostParts[ArrayLen(hostParts) - 1] & "." & hostParts[ArrayLen(hostParts)]>
    <cfelse>
        <cfset zoneName = getLocalRecords.hostname>
    </cfif>

    <!--- Add transparent zone declaration (only once per zone) --->
    <cfif NOT StructKeyExists(processedZones, zoneName)>
        <cfset conf = conf & '    local-zone: "' & zoneName & '." transparent' & nl>
        <cfset processedZones[zoneName] = true>
    </cfif>

    <!--- Add local-data entry.

         Strip CR/LF from both fields first. They are admin-supplied and land
         verbatim in a config file, so a newline would let an operator append
         arbitrary Unbound directives (#304).

         TXT needs different quoting from every other type. Unbound's
         local-data value is itself a quoted string, and a TXT record's rdata
         must ALSO be quoted in zone-file syntax whenever it contains spaces
         or semicolons -- which every realistic TXT value does (SPF, DKIM,
         DMARC all contain both, and an unquoted semicolon starts a zone-file
         comment that silently truncates the record). Double quotes cannot
         nest inside double quotes, and escaping them as \" produces a literal
         quote character in the rdata rather than a delimiter. Unbound accepts
         single quotes for config values, so TXT is emitted single-quoted on
         the outside with the value double-quoted inside.

         Any quotes the admin typed, including the \" workaround people
         discover for this bug, are stripped before re-quoting so the record
         renders once, correctly. --->
    <cfset ldHost  = Replace(Replace(getLocalRecords.hostname, Chr(13), "", "ALL"), Chr(10), "", "ALL")>
    <cfset ldValue = Replace(Replace(getLocalRecords.value, Chr(13), "", "ALL"), Chr(10), "", "ALL")>

    <cfif getLocalRecords.record_type EQ "TXT">
        <cfset ldValue = Trim(REReplace(ldValue, '^[\\"]+|[\\"]+$', "", "ALL"))>
        <cfset conf = conf & "    local-data: '" & ldHost & '. IN TXT "' & ldValue & '"' & "'" & nl>
    <cfelse>
        <cfset conf = conf & '    local-data: "' & ldHost & '. IN ' & getLocalRecords.record_type & ' ' & ldValue & '"' & nl>
    </cfif>
</cfloop>

<cfif getLocalRecords.recordcount EQ 0>
    <cfset conf = conf & chr(35) & " No local DNS overrides configured." & nl>
</cfif>

<!--- Write local.conf --->
<cfscript>fileWrite("/etc/unbound/conf.d/local.conf", conf, "utf-8");</cfscript>

<!--- Restart Unbound --->
<cfexecute name="/usr/local/bin/docker"
    arguments="container restart hermes_unbound"
    variable="restartResult"
    errorVariable="restartError"
    timeout="30" />
