version: '2'

networks:
  hermesexternal:
    external: true

HermesSEG_nextcloud_redis:
    image: redis
    container_name: HermesSEG_nextcloud_redis
    logging:
      options:
        max-size: 10m
    networks:
      - hermesexternal
    volumes:
      - redis:/var/lib/redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    restart: unless-stopped

  HermesSEG_nextcloud:
    image: nextcloud:latest
    container_name: HermesSEG_nextcloud
    logging:
      options:
        max-size: 10m
    networks:
      - hermesexternal
    ports:
      - 8081:80
    volumes:
      - nextcloud:/var/www/html
#Uncomment and then uncomment and set smb connection parameters under the volumes section below
      #- smb:/mnt/smb

    environment:
      - TZ=${TIMEZONE}
      - MYSQL_HOST=localhost
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - REDIS_HOST=HermesSEG_nextcloud_redis
      - REDIS_HOST_PASSWORD=${REDIS_PASSWORD}
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
      - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_TRUSTED_DOMAINS}
#=== EMAIL SETTINGS BELOW DO NOT SEEM TO WORK UNDER DOCKER ===
#=== THEY ARE LEFT FOR REFERENCE ONLY. DO NOT CONFIGURE ON THIS FILE BUT RATHER CONFIGURE IN THE NEXTCLOUD BASIC SETTINS OF THE WEB GUI
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_SECURE=${SMTP_SECURE}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_AUTHTYPE=${SMTP_AUTHTYPE}
      - SMTP_NAME=${SMTP_NAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - MAIL_FROM_ADDRESS=${MAIL_FROM_ADDRESS}
      - MAIL_DOMAIN=${MAIL_DOMAIN}
      - OVERWRITEPROTOCOL=https
      #- APACHE_DISABLE_REWRITE_IP=1
#Uncomment and set to Traefik IP range
      - TRUSTED_PROXIES=${TRUSTED_PROXIES}
    env_file:
      - db.env
    depends_on:
      - HermesSEG_nextcloud_redis
      - HermesSEG_nextcloud_db
    restart: unless-stopped

volumes:

  redis:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/data/docker/nextcloud/redis

  nextcloud:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/data/docker/nextcloud/nextcloud_data